name: Senior Project Offer
description: Create a senior project offer
title: "[OFFER]: "
labels: ["capstone"]
assignees: ["doganulus"] # Assign the current coordinator here
body:
  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      placeholder: Describe the project in detail
    validations:
      required: true
