name: New Senior Project Offer
description: Create a new senior project offer
title: "Project: "
assignees: ["doganulus"] # Assign the current coordinator here
projects:
  - bouncmpe/16 # Rolling project board
body:
  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Provide a clear, concise, and complete description of the project.
      placeholder: |
        What is the main goal of the project?
        What kind of tasks will students perform?
        What is the expected output/deliverable?
    validations:
      required: true