name: New Project Offer
description: Create a new senior project offer
title: "Project: "
assignees: [] # Assign the current coordinator here
projects:
  - bouncmpe/16 # Fall 2024
body:
  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      placeholder: Describe the project in detail
    validations:
      required: true
